#Manual AccuKnox IaC Scan.
name: AccuKnox IaC Scan Workflow

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Run IaC scan
        uses: accuknox/iac-scan-action@v0.0.1
        with:
          token: ${{ secrets.TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          soft_fail: true
    